[2023-12-11 18:22:07,942] INFO _log() L186  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.9:5000 - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:22:07,958] INFO _log() L186  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:22:08,077] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:41:20,166] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\Dados\\Pós\\Github Pós\\mvp-qualidade-seguranca-sistemas-inteligentes\\MVP\\api\\MVP_SPRINT_IV_API\\test_modelos.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:41:20,170] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\Dados\\Pós\\Github Pós\\mvp-qualidade-seguranca-sistemas-inteligentes\\MVP\\api\\MVP_SPRINT_IV_API\\test_modelos.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:41:22,297] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:55:47,362] INFO _log() L186  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.9:5000 - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:55:47,369] INFO _log() L186  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:55:47,424] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:01,467] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:56:01,476] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:01] "[33mGET /partidas HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:05,990] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:56:05,994] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:05] "[33mGET /partidas?homeTeam=Bahia HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:06,086] ERROR log_exception() L1449 Exception on /partida [POST] - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py", line 83, in predict
    scaler = Model.carrega_modelo(ml_scaler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\model\modelo.py", line 17, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
                        ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ml_model/scaler.pkl'
[2023-12-11 18:56:06,097] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:06,177] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:06] "[35m[1mPOST /partida HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:06,182] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask_cors\\extension.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:06,190] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask_openapi3\\scaffold.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:06,196] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask_openapi3\\do_wrapper.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:07,825] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:18,757] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:56:18,772] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:18] "[33mGET /partidas HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:43,135] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:56:43,138] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:43] "[33mGET /partidas?homeTeam=Botafogo-RJ HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:43,336] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\logging\\handlers.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:43,453] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:43] "[35m[1mPOST /partida HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:43,455] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\cli.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:43,463] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\server.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
